travis:
  secure:
    BINSTAR_TOKEN: lmj5TPN0b9yMadop9HkI45zWax9jU+j7J61osh/VSL11xlyKSSH/1VDpXuUg1I8UE+qxQbaWAEDwaeWc7K88UizcVDoOuK/OSf/ZSIHGX0HWNXuJVCOWhu5ebmg4DzJkczYp1UFw8WMvtjpMF3v2I+ICk8zBudCeWsu+NcwU7/vI4zGQmueNyUgD+eeFlOkKx5UphUGB4m5QdtrSXiiLmTKVbpqvznRyJQpdlDWWrscm8JThPpw7x4vQHJtAXtwJD2BN2Fng+0GAIeqWbsSnZ7RfyL/x7ph91wHGDZv0qxNSXnp4uXOc9T1vkzDVg7VyX4rhIduKuvGWcWa1rNlvysPEkYbl37QI0B07/l7+bHKC56gKZEc2qcFk4p7cLB+JMoynTNzraIyC3WkpWaxE3OZRH2FJXEaY2tfOIOZ3AcvVkr76Wvbe3f/mCTWWDbtCbSKE/b6WO+Xaq9kZKcZq1fHOOOvlAG2MvfkL02rIxG0xAcX/OvqomvZMVulrdUkThYOdOi8mBOBtOWT9qbNDHYghAl7hnXmz4oznN/Mh20zntOjzkMTNiVVaHr3r6UqFcV8Q0DWhK9AZN14Eq84xOt6i8Sw5e6k+uetnfS7driVFTArhv5kViRSVNI+OwDp2RKPRKY9+SIbpXB195b2K3dTDrmre8bglPD2zmvrVmYs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
